### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Silas123Go** [Creeper76/MegaHackColorMod#1]
are you ever going to be able to hotfix this to work with v7.1 gm2? i like this version way more than the original made by ikszyon because of the profile system, and would like to see this hotfixed so i can use it eventually

**Comment by Creeper76** [comment]
I’ll try to update it within the next day or 2. Sorry!

**Comment by Silas123Go** [comment]
its okay! i was just making sure you were still updating the mod, just a little reminder

**Comment by Creeper76** [comment]
I updated it to work with the latest version.
